-- ============================================================
-- CDKT Seed Data
-- Generated from server/db/seed.ts
-- Inserts default roles, admin user, permissions, content types,
-- categories, home sections, system pages, and chatbot settings.
-- Safe to re-run (uses INSERT IGNORE / ON DUPLICATE KEY UPDATE).
-- ============================================================

USE `cdkt_admin`;

-- ------------------------------------------------------------
-- Default Roles
-- ------------------------------------------------------------

INSERT INTO `roles` (`id`, `name`, `description`, `is_system`) VALUES
  (1, 'Super Admin', 'Quản trị viên tối cao - Toàn quyền hệ thống', 1),
  (2, 'Biên tập viên', 'Biên tập viên nội dung - Quản lý tin tức, bài viết', 0),
  (3, 'Người kiểm duyệt', 'Kiểm duyệt nội dung trước khi xuất bản', 0)
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);

-- ------------------------------------------------------------
-- Default Admin User (password: Admin@123456)
-- bcrypt hash of Admin@123456
-- ------------------------------------------------------------

INSERT IGNORE INTO `users` (`id`, `username`, `email`, `password_hash`, `role_id`, `is_active`)
VALUES (1, 'admin', 'admin@cdkt.gov.vn', '$2b$10$qJ5GQGQGQGQGQGQGQGQGQ.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX', 1, 1);
-- NOTE: The actual hash is generated by server/db/seed.ts at runtime.
-- For fresh deploys, run: npx tsx server/db/seed.ts

-- ------------------------------------------------------------
-- Permissions Matrix (Super Admin gets all)
-- ------------------------------------------------------------

INSERT INTO `permissions` (`role_id`, `resource`, `can_create`, `can_read`, `can_update`, `can_delete`, `can_publish`, `can_archive`, `can_test`) VALUES
  (1, 'users', 1, 1, 1, 1, 0, 0, 0),
  (1, 'roles', 1, 1, 1, 1, 0, 0, 0),
  (1, 'news', 1, 1, 1, 1, 1, 1, 0),
  (1, 'home_sections', 1, 1, 1, 1, 0, 0, 0),
  (1, 'pages', 1, 1, 1, 1, 1, 0, 0),
  (1, 'categories', 1, 1, 1, 1, 0, 0, 0),
  (1, 'media', 1, 1, 1, 1, 0, 0, 0),
  (1, 'settings', 1, 1, 1, 1, 0, 0, 0),
  (1, 'submissions', 1, 1, 1, 1, 0, 0, 0),
  (1, 'documents', 1, 1, 1, 1, 1, 1, 0),
  (1, 'faq', 1, 1, 1, 1, 1, 1, 0),
  (1, 'analytics', 0, 1, 0, 0, 0, 0, 0),
  (1, 'chatbot_knowledge', 1, 1, 1, 1, 1, 1, 0),
  (1, 'chatbot_settings', 0, 1, 1, 0, 0, 0, 1)
ON DUPLICATE KEY UPDATE `can_create` = VALUES(`can_create`);

-- Editor permissions
INSERT INTO `permissions` (`role_id`, `resource`, `can_create`, `can_read`, `can_update`, `can_delete`, `can_publish`, `can_archive`, `can_test`) VALUES
  (2, 'news', 1, 1, 1, 0, 0, 0, 0),
  (2, 'media', 1, 1, 0, 0, 0, 0, 0),
  (2, 'pages', 0, 1, 1, 0, 0, 0, 0),
  (2, 'categories', 0, 1, 0, 0, 0, 0, 0),
  (2, 'chatbot_knowledge', 1, 1, 1, 0, 0, 0, 0)
ON DUPLICATE KEY UPDATE `can_create` = VALUES(`can_create`);

-- ------------------------------------------------------------
-- System Content Types
-- ------------------------------------------------------------

INSERT INTO `content_types` (`name`, `slug`, `icon`, `display_order`, `is_system`) VALUES
  ('Bản tin & Tin tức', 'news', 'fa-solid fa-newspaper', 1, 1),
  ('Tấm gương tiêu biểu', 'role_model', 'fa-solid fa-award', 2, 1),
  ('Mô hình tái hòa nhập', 'reintegration', 'fa-solid fa-people-roof', 3, 1),
  ('Văn bản pháp luật', 'document', 'fa-solid fa-file-lines', 4, 1),
  ('Giải đáp pháp luật', 'faq', 'fa-solid fa-circle-question', 5, 1)
ON DUPLICATE KEY UPDATE `slug` = `slug`;

-- ------------------------------------------------------------
-- Default Categories
-- ------------------------------------------------------------

INSERT INTO `categories` (`name`, `slug`, `type`, `parent_id`, `display_order`) VALUES
  ('Tin nổi bật', 'tin-noi-bat', 'news', NULL, 1),
  ('Tin hoạt động', 'tin-hoat-dong', 'news', NULL, 2),
  ('Tin địa phương', 'tin-dia-phuong', 'news', NULL, 3),
  ('Tấm gương tiêu biểu', 'tam-guong-tieu-bieu', 'role_model', NULL, 1),
  ('Mô hình tái hòa nhập', 'mo-hinh-tai-hoa-nhap', 'reintegration', NULL, 1),
  ('Văn bản pháp luật', 'van-ban-phap-luat', 'document', NULL, 1),
  ('Hỏi đáp pháp luật', 'hoi-dap-phap-luat', 'faq', NULL, 1)
ON DUPLICATE KEY UPDATE `slug` = `slug`;

-- ------------------------------------------------------------
-- Home Sections (default layout)
-- ------------------------------------------------------------

INSERT INTO `home_sections` (`type`, `display_order`, `is_visible`, `config`) VALUES
  ('hero', 1, 1, '{"title":"Con Đường Hướng Thiện","subtitle":"Cổng thông tin hỗ trợ người hoàn lương tái hòa nhập cộng đồng","description":"Cục Cảnh sát quản lý tạm giữ, tạm giam và thi hành án hình sự tại cộng đồng (C11) - Bộ Công an"}'),
  ('stats', 2, 1, NULL),
  ('news', 3, 1, '{"title":"Tin tức & Bản tin","count":6}'),
  ('role_models', 4, 1, '{"title":"Tấm gương hoàn lương tiêu biểu","count":4}'),
  ('reintegration', 5, 1, '{"title":"Mô hình tái hòa nhập cộng đồng","count":4}'),
  ('documents', 6, 1, '{"title":"Văn bản quy phạm pháp luật","count":6}'),
  ('support_form', 7, 1, '{"title":"Đăng ký hỗ trợ tư vấn 24/7"}'),
  ('links', 8, 1, '{"title":"Liên kết hữu ích"}')
ON DUPLICATE KEY UPDATE `type` = `type`;

-- ------------------------------------------------------------
-- System Pages
-- ------------------------------------------------------------

INSERT INTO `pages` (`slug`, `title`, `is_system`) VALUES
  ('home', 'Trang chủ', 1),
  ('about', 'Giới thiệu', 1),
  ('contact', 'Liên hệ', 1)
ON DUPLICATE KEY UPDATE `slug` = `slug`;

-- ------------------------------------------------------------
-- Default Chatbot Settings (disabled by default)
-- ------------------------------------------------------------

INSERT INTO `chatbot_settings` (`id`, `enabled`) VALUES (1, 0)
ON DUPLICATE KEY UPDATE `id` = `id`;
