#!/usr/bin/env node
/**
 * Self-host the Inter webfont.
 *
 * The portal currently pulls Inter from fonts.googleapis.com on every page
 * view. For a Bộ Công an site that means (a) every visitor's IP and User-Agent
 * reach a third party on a request the visitor never chose to make, and
 * (b) the typography degrades whenever that CDN is slow or filtered — which it
 * is on a number of Vietnamese networks.
 *
 * Run this once on a machine with internet access:
 *
 *     node scripts/fetch-fonts.mjs
 *
 * It writes public/assets/fonts/*.woff2 plus public/assets/fonts/inter.css.
 * nuxt.config.ts picks that file up automatically on the next build and stops
 * emitting the Google <link> tags — no config edit needed. Re-run it to
 * refresh; delete the folder to fall back to the CDN.
 */
import { mkdir, writeFile, readdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'public', 'assets', 'fonts')

// Only the weights app/assets/css/main.css and the templates actually ask for.
const CSS_URL = 'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap'

// Google serves woff2 only to browsers it recognises; an unknown agent gets ttf.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

async function get(url, asText) {
  const response = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!response.ok) throw new Error(`${response.status} ${response.statusText} — ${url}`)
  return asText ? response.text() : Buffer.from(await response.arrayBuffer())
}

const main = async () => {
  console.log('→ fetching the Inter stylesheet from Google')
  const css = await get(CSS_URL, true)

  const remoteUrls = [...new Set([...css.matchAll(/url\((https:\/\/[^)]+\.woff2)\)/g)].map(m => m[1]))]
  if (remoteUrls.length === 0) throw new Error('no woff2 URLs in the response — Google changed its format')

  await mkdir(OUT_DIR, { recursive: true })

  // The remote filenames are opaque hashes; name the files after their weight
  // and subset so a future reviewer can tell what is in the folder.
  const names = new Map()
  let index = 0
  for (const url of remoteUrls) {
    const block = css.slice(0, css.indexOf(url))
    const weight = /font-weight:\s*(\d+)[^{]*$/.exec(block.split('@font-face').pop() ?? '')?.[1] ?? 'x'
    const subset = /\/\*\s*([a-z-]+)\s*\*\/(?:(?!\/\*)[\s\S])*$/.exec(block)?.[1] ?? `set${index}`
    names.set(url, `inter-${subset}-${weight}.woff2`)
    index++
  }

  let localCss = css
  for (const [url, name] of names) {
    process.stdout.write(`→ ${name} `)
    const bytes = await get(url, false)
    await writeFile(join(OUT_DIR, name), bytes)
    console.log(`(${Math.round(bytes.length / 1024)} KB)`)
    localCss = localCss.split(url).join(`/assets/fonts/${name}`)
  }

  const header = [
    '/*',
    ' * Inter, self-hosted. Generated by scripts/fetch-fonts.mjs — do not edit by hand.',
    ' * Inter is licensed under the SIL Open Font License 1.1.',
    ' * Re-run the script to refresh; delete this folder to fall back to the Google CDN.',
    ' */',
    '',
  ].join('\n')
  await writeFile(join(OUT_DIR, 'inter.css'), header + localCss)

  const written = await readdir(OUT_DIR)
  console.log(`\n✓ ${written.length} files in public/assets/fonts`)
  console.log('  Rebuild (npm run build) and the Google <link> tags disappear on their own.')
}

if (existsSync(join(OUT_DIR, 'inter.css'))) {
  console.log('Refreshing the existing public/assets/fonts …')
}

main().catch((error) => {
  console.error(`\n✗ ${error.message}`)
  console.error('  Nothing changed; the site keeps loading Inter from Google.')
  process.exit(1)
})
